<a href="https://colab.research.google.com/github/EnidFerns/ml/blob/main/covidindication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dataset courtesy ->  https://data.gov.il/dataset/covid-19

translation courtesy -> https://github.com/nshomron

In [50]:
#takes in symptoms and lets you know the possibility of you being positive:) using svm classifier -> 97% accuracy

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/corona_tested_individuals_ver_0083.english.csv')

In [3]:
df.head()

test_date  cough  ...         test_indication  corona_result
0  12/11/2020    0.0  ...                   Other       negative
1  12/11/2020    0.0  ...                   Other       negative
2  12/11/2020    0.0  ...                   Other       negative
3  12/11/2020    0.0  ...                   Other       negative
4  12/11/2020    0.0  ...  Contact with confirmed       negative

[5 rows x 10 columns]

In [4]:
df.isnull().sum()

test_date                 0
cough                     1
fever                     1
sore_throat               1
shortness_of_breath       1
head_ache                 1
gender                  145
age_60_and_above       1375
test_indication           1
corona_result             1
dtype: int64

In [5]:
df

test_date  cough  ...         test_indication  corona_result
0      12/11/2020    0.0  ...                   Other       negative
1      12/11/2020    0.0  ...                   Other       negative
2      12/11/2020    0.0  ...                   Other       negative
3      12/11/2020    0.0  ...                   Other       negative
4      12/11/2020    0.0  ...  Contact with confirmed       negative
...           ...    ...  ...                     ...            ...
45036  09/11/2020    0.0  ...                   Other       negative
45037  09/11/2020    1.0  ...                   Other       negative
45038  09/11/2020    0.0  ...                   Other       negative
45039  09/11/2020    0.0  ...                   Other       negative
45040           0    NaN  ...                     NaN            NaN

[45041 rows x 10 columns]

In [6]:
df.drop(columns='test_date',inplace = True)
df.drop(columns='gender',inplace = True)

In [7]:
df['corona_result'].unique()

array(['negative', 'positive', 'other', nan], dtype=object)

In [8]:
categ = {'corona_result':{'negative':1,'positive':0}}
df.replace(categ, inplace =True)

In [9]:
df = df[df['corona_result']!='other']

In [10]:
df

cough  fever  ...         test_indication  corona_result
0        0.0    0.0  ...                   Other              1
1        0.0    1.0  ...                   Other              1
2        0.0    0.0  ...                   Other              1
3        0.0    0.0  ...                   Other              1
4        0.0    1.0  ...  Contact with confirmed              1
...      ...    ...  ...                     ...            ...
45036    0.0    0.0  ...                   Other              1
45037    1.0    1.0  ...                   Other              1
45038    0.0    0.0  ...                   Other              1
45039    0.0    0.0  ...                   Other              1
45040    NaN    NaN  ...                     NaN            NaN

[44657 rows x 8 columns]

In [11]:
df['corona_result'].unique()

array([1, 0, nan], dtype=object)

In [12]:
df['age_60_and_above'].unique()

array(['No', 'Yes', nan], dtype=object)

In [13]:
categ = {'age_60_and_above':{'No':1,'Yes':0}}
df.replace(categ, inplace =True)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


In [14]:
df['test_indication'].unique()

array(['Other', 'Contact with confirmed', 'Abroad', nan], dtype=object)

In [15]:
categ = {'test_indication':{'Other':3,'Contact with confirmed':1, 'Abroad':0}}
df.replace(categ, inplace =True)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


In [16]:
df['test_indication'].unique()

array([ 3.,  1.,  0., nan])

In [17]:
df['corona_result'].unique()

array([1, 0, nan], dtype=object)

In [18]:
df.describe()

cough         fever  ...  age_60_and_above  test_indication
count  44656.000000  44656.000000  ...      43304.000000     44656.000000
mean       0.019079      0.013011  ...          0.833179         2.939762
std        0.136805      0.113321  ...          0.372820         0.345937
min        0.000000      0.000000  ...          0.000000         0.000000
25%        0.000000      0.000000  ...          1.000000         3.000000
50%        0.000000      0.000000  ...          1.000000         3.000000
75%        0.000000      0.000000  ...          1.000000         3.000000
max        1.000000      1.000000  ...          1.000000         3.000000

[8 rows x 7 columns]

In [19]:
X = np.mean(df['corona_result'])
X = int(X)
df['corona_result'] = df['corona_result'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
X = np.mean(df['test_indication'])
X = int(X)
df['test_indication'] = df['test_indication'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [21]:
X = np.mean(df['age_60_and_above'])
X = int(X)
df['age_60_and_above'] = df['age_60_and_above'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [22]:
X = np.mean(df['fever'])
X = int(X)
df['fever'] = df['fever'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
X = np.mean(df['head_ache'])
X = int(X)
df['head_ache'] = df['head_ache'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [24]:
X = np.mean(df['cough'])
X = int(X)
df['cough'] = df['cough'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [25]:
X = np.mean(df['shortness_of_breath'])
X = int(X)
df['shortness_of_breath'] = df['shortness_of_breath'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
X = np.mean(df['sore_throat'])
X = int(X)
df['sore_throat'] = df['sore_throat'].fillna(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [27]:
df.isnull().sum()

cough                  0
fever                  0
sore_throat            0
shortness_of_breath    0
head_ache              0
age_60_and_above       0
test_indication        0
corona_result          0
dtype: int64

In [28]:
df.describe()

cough         fever  ...  test_indication  corona_result
count  44657.000000  44657.000000  ...     44657.000000    44657.00000
mean       0.019079      0.013010  ...         2.939741        0.97071
std        0.136803      0.113319  ...         0.345961        0.16862
min        0.000000      0.000000  ...         0.000000        0.00000
25%        0.000000      0.000000  ...         3.000000        1.00000
50%        0.000000      0.000000  ...         3.000000        1.00000
75%        0.000000      0.000000  ...         3.000000        1.00000
max        1.000000      1.000000  ...         3.000000        1.00000

[8 rows x 8 columns]

In [29]:
df.isnull().sum()

cough                  0
fever                  0
sore_throat            0
shortness_of_breath    0
head_ache              0
age_60_and_above       0
test_indication        0
corona_result          0
dtype: int64

In [30]:
x = df.iloc[:,0:7].values

In [31]:
y = df.iloc[:,7:].values.reshape(-1,1)

In [32]:
x

array([[0., 0., 0., ..., 0., 1., 3.],
       [0., 1., 0., ..., 0., 1., 3.],
       [0., 0., 0., ..., 0., 0., 3.],
       ...,
       [0., 0., 0., ..., 0., 0., 3.],
       [0., 0., 0., ..., 0., 1., 3.],
       [0., 0., 0., ..., 0., 0., 2.]])

In [33]:
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [34]:
df.describe()

cough         fever  ...  test_indication  corona_result
count  44657.000000  44657.000000  ...     44657.000000    44657.00000
mean       0.019079      0.013010  ...         2.939741        0.97071
std        0.136803      0.113319  ...         0.345961        0.16862
min        0.000000      0.000000  ...         0.000000        0.00000
25%        0.000000      0.000000  ...         3.000000        1.00000
50%        0.000000      0.000000  ...         3.000000        1.00000
75%        0.000000      0.000000  ...         3.000000        1.00000
max        1.000000      1.000000  ...         3.000000        1.00000

[8 rows x 8 columns]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.3)

In [37]:
from sklearn.svm import SVC

In [38]:
class_svc =SVC(kernel = 'linear')

In [39]:
class_svc.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
predy = class_svc.predict(x_test)

In [41]:
predy

array([1, 1, 1, ..., 1, 1, 1])

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [43]:
cm = confusion_matrix(y_test,predy)

In [44]:
cm

array([[  115,   298],
       [    6, 12979]])

In [45]:
accuracy_score(y_test,predy)

0.9773100462755635

cough	0:no 1:yes

fever	0:no 1:yes

sore_throat 0:no 1:yes	

shortness_of_breath	0:no 1:yes

head_ache	0:no 1: yes

age_60_and_above 0:Yes 1:No	

test_indication	'Other':3, 'Contact with confirmed':1,  'Abroad':0

corona_result 1:negative 0:positive

In [49]:
f = class_svc.predict([[0,0,1,0,0,0,1]])
if f == 0:
  print('Please do a test as soon as possible')
else:
  print("You're fine for now. Don't panic!")

Please do a test as soon as possible
