<a href="https://colab.research.google.com/github/EnidFerns/ml/blob/main/fuel_consumption_using_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

i/p engine size

model gives expected CO2 emissions

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/FuelConsumptionCo2.csv')

In [5]:
df

MODELYEAR   MAKE  ... FUELCONSUMPTION_COMB_MPG CO2EMISSIONS
0          2014  ACURA  ...                       33          196
1          2014  ACURA  ...                       29          221
2          2014  ACURA  ...                       48          136
3          2014  ACURA  ...                       25          255
4          2014  ACURA  ...                       27          244
...         ...    ...  ...                      ...          ...
1062       2014  VOLVO  ...                       24          271
1063       2014  VOLVO  ...                       25          264
1064       2014  VOLVO  ...                       24          271
1065       2014  VOLVO  ...                       25          260
1066       2014  VOLVO  ...                       22          294

[1067 rows x 13 columns]

In [8]:
x = df.iloc[:,4].values.reshape(-1,1)
y = df.iloc[:,-1].values.reshape(-1,1)

In [9]:
x

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [10]:
y

array([[196],
       [221],
       [136],
       ...,
       [271],
       [260],
       [294]])

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
train_x,test_x,train_y,test_y = train_test_split(x,y, test_size=0.2)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
Lin = LinearRegression()

In [18]:
Lin.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
pred_y = Lin.predict(test_x)

In [21]:
np.concatenate((test_y,pred_y), axis =1)

array([[232.        , 261.76488621],
       [212.        , 230.45427252],
       [177.        , 195.22983211],
       [277.        , 242.19575265],
       [230.        , 261.76488621],
       [216.        , 203.05748554],
       [340.        , 367.43820743],
       [414.        , 312.64463347],
       [380.        , 332.21376703],
       [181.        , 203.05748554],
       [350.        , 308.73080675],
       [297.        , 281.33401977],
       [207.        , 203.05748554],
       [202.        , 222.62661909],
       [260.        , 269.59253964],
       [297.        , 304.81698004],
       [344.        , 332.21376703],
       [292.        , 296.98932662],
       [259.        , 265.67871292],
       [283.        , 269.59253964],
       [246.        , 203.05748554],
       [386.        , 304.81698004],
       [345.        , 343.95524716],
       [244.        , 261.76488621],
       [209.        , 203.05748554],
       [318.        , 320.47228689],
       [205.        , 203.05748554],
 

In [22]:
from sklearn import metrics

In [23]:
metrics.mean_absolute_error(test_y,pred_y)

20.745306976480332

In [25]:
Lin.predict([[700]])

array([[27521.56793408]])

In [26]:
Lin.intercept_# theorotical try

array([124.7809513])

In [27]:
Lin.coef_

array([[39.13826712]])

In [28]:
124.7809513+ (39.13826712)*700

27521.5679353