<a href="https://colab.research.google.com/github/EnidFerns/ml/blob/main/GameKNN(notworking).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#23 M

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/game_knn.csv')

In [4]:
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [6]:
le =LabelEncoder()
label= le.fit_transform(df['Gender'])

In [7]:
label#male-0,female-1

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [8]:
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [9]:
df = df.drop('Gender',axis = 'columns')

In [10]:
df

Name  Age     Sport
0    A   32  Football
1    B   40   Neither
2    C   16   Cricket
3    D   34   Cricket
4    E   55   Neither
5    F   40   Cricket
6    G   20   Neither
7    H   15   Cricket
8    I   55  Football
9    J   15  Football

In [11]:
df.insert(2,'Gender',label)

In [12]:
df

Name  Age  Gender     Sport
0    A   32       1  Football
1    B   40       1   Neither
2    C   16       0   Cricket
3    D   34       0   Cricket
4    E   55       1   Neither
5    F   40       1   Cricket
6    G   20       0   Neither
7    H   15       1   Cricket
8    I   55       0  Football
9    J   15       1  Football

In [13]:
sc=StandardScaler()

In [14]:
x = df.iloc[:,1:3].values

In [15]:
x = sc.fit_transform(x)
x

array([[-0.0135844 ,  0.81649658],
       [ 0.52979156,  0.81649658],
       [-1.10033631, -1.22474487],
       [ 0.12225959, -1.22474487],
       [ 1.54862147,  0.81649658],
       [ 0.52979156,  0.81649658],
       [-0.82864833, -1.22474487],
       [-1.1682583 ,  0.81649658],
       [ 1.54862147, -1.22474487],
       [-1.1682583 ,  0.81649658]])

In [16]:
y = df.iloc[:,3].values
y

array(['Football', 'Neither', 'Cricket', 'Cricket', 'Neither', 'Cricket',
       'Neither', 'Cricket', 'Football', 'Football'], dtype=object)

In [17]:
y = le.fit_transform(y)

In [18]:
y#1-football, 2-neither,0-cricket

array([1, 2, 0, 0, 2, 0, 2, 0, 1, 1])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [21]:
x_train

array([[-1.10033631, -1.22474487],
       [ 1.54862147, -1.22474487],
       [ 1.54862147,  0.81649658],
       [-1.1682583 ,  0.81649658],
       [-0.0135844 ,  0.81649658],
       [ 0.12225959, -1.22474487],
       [ 0.52979156,  0.81649658],
       [ 0.52979156,  0.81649658]])

In [22]:
x_test

array([[-0.82864833, -1.22474487],
       [-1.1682583 ,  0.81649658]])

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
classifier = KNeighborsClassifier(n_neighbors=3,metric='euclidean')

In [25]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [26]:
y_pred = classifier.predict(x_test)

In [27]:
y_pred

array([0, 0])

In [28]:
y_test

array([2, 1])

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y_test,y_pred)*100

0.0

In [31]:
classifier.predict([[23,1]])

array([0])

In [32]:
classifier.predict([[32,1]])

array([0])