<a href="https://colab.research.google.com/github/EnidFerns/ml/blob/main/multiple_linear_regression_Advertising.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

given dataframe: all ads shown(amount spent on each section:tv radio newspaper is given)

i/p investment on ads( tv then radio then newspaper)

o/p sales expected

1)make an estimator then create aodel to see how many sales are made

2)which factor affects the sale the most

In [5]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/Advertising.csv')

In [4]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [7]:
x = df['TV'].values.reshape(-1,1)
y = df['Sales'].values.reshape(-1,1)

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size =0.2,random_state =0)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
Lin = LinearRegression()

In [13]:
Lin.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
pred_y = Lin.predict(test_x)

In [15]:
np.concatenate((test_y,pred_y), axis = 1)

array([[11.3       , 10.92912965],
       [ 8.4       ,  9.88399105],
       [12.        , 12.08313684],
       [25.4       , 22.93189318],
       [16.7       , 16.42699412],
       [ 8.7       , 10.22148373],
       [ 7.2       ,  7.63585439],
       [18.2       , 20.23195181],
       [ 9.2       ,  8.45781235],
       [16.6       , 17.91849399],
       [24.2       , 21.38595901],
       [10.6       , 11.90894708],
       [15.5       , 15.68668762],
       [20.6       , 17.38503783],
       [11.8       , 11.32105662],
       [13.2       , 13.70527904],
       [17.4       , 21.62002651],
       [ 1.6       ,  7.20037998],
       [14.7       , 11.22851831],
       [17.        , 18.77855596],
       [26.2       , 22.81758114],
       [10.3       , 14.7994085 ],
       [16.1       , 16.6937222 ],
       [12.9       , 14.33127351],
       [ 8.1       , 10.07451111],
       [15.2       , 13.86313851],
       [17.6       , 16.17659633],
       [22.6       , 18.32130782],
       [16.6       ,

In [23]:
test_y-pred_y

array([[ 0.37087035],
       [-1.48399105],
       [-0.08313684],
       [ 2.46810682],
       [ 0.27300588],
       [-1.52148373],
       [-0.43585439],
       [-2.03195181],
       [ 0.74218765],
       [-1.31849399],
       [ 2.81404099],
       [-1.30894708],
       [-0.18668762],
       [ 3.21496217],
       [ 0.47894338],
       [-0.50527904],
       [-4.22002651],
       [-5.60037998],
       [ 3.47148169],
       [-1.77855596],
       [ 3.38241886],
       [-4.4994085 ],
       [-0.5937222 ],
       [-1.43127351],
       [-1.97451111],
       [ 1.33686149],
       [ 1.42340367],
       [ 4.27869218],
       [-2.75555956],
       [-0.02857694],
       [ 1.64707837],
       [ 5.71074142],
       [-6.34198446],
       [ 1.4809533 ],
       [-2.28080875],
       [-1.48019741],
       [-0.70656035],
       [ 0.89600228],
       [ 2.71441779],
       [-1.32313351]])

In [19]:
np.abs(test_y-pred_y).mean()

2.01486731475948

In [22]:
Lin.predict([[20000]])

array([[1095.84831049]])

In [24]:
# If i invest 20k rs in tv ads ill get a sale of 1095+/-2.01 

Corelation function: which vakue is dependant on another function in the column

In [25]:
df.corr()#theoretical

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

tv with tv is 100% related
tv radio 0%


tv and sales is 90%
radio correalted to sales with 35%
sales on newspaper is 16%

In [26]:
#practically proving that tv gives the most sales.. u add radio and newspaper as x values

In [28]:
x = df[['TV','Radio']].values

In [29]:
#repeat all steps with new x

In [30]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size =0.2,random_state =0)

In [31]:
Lin.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
pred_ynew = Lin.predict(test_x)

In [33]:
np.abs(test_y-pred_y).mean() #only with tv

2.01486731475948

In [34]:
np.abs(test_y-pred_ynew).mean() #with radio and tv # error reduced to 30%

1.4032867136894107

In [35]:
x = df[['TV','Radio','Newspaper']].values

In [36]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size =0.2,random_state =0)

In [37]:
Lin.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
pred_ynew2 = Lin.predict(test_x)

In [39]:
np.abs(test_y-pred_y).mean() #only with tv

2.01486731475948

In [40]:
np.abs(test_y-pred_ynew).mean() #with radio and tv # error reduced to 30%

1.4032867136894107

In [41]:
np.abs(test_y-pred_ynew2).mean() #with radio and tv and newspaper # error increased 0.1(no effect)

1.4170313030600667

## **CONCLUSION:**

There's no effect of newspaper on sales